---
meta:
  name:    $(basename $PWD)
  target:  ${fly_target}
  url:     ${fly_target_url}

  initial_version: 0.1.0

  git:
    email:  ((git-commit-email))
    name:   ((git-commit-name))

  aws:
    bucket:      (( grab meta.pipeline ))
    region_name: us-east-1
    access_key:  ((aws-access-key))
    secret_key:  ((aws-secret-key))
    charts_uri:  $(helm repo list | (grep s3:// || { echo "dummy s3://my-helm-bucket/charts"; }) | awk '{print $2}')

  github:
    owner:  $(basename $(dirname $PWD))
    repo:   $(basename $PWD)
    branch: $(git branch --no-color | awk '{print $2}')
    private_key:  ((github-private-key))
    access_token: ((github-access-token))

  dockerhub:
    username:   ((docker-hub-username))
    password:   ((docker-hub-password))
    repository: ((dockerhub-username))/$(basename $PWD)

  slack:
    webhook:       ((slack-webhook))
    username:      ((slack-username))
    icon:          ((slack-icon-url))
    channel:       "#$(basename $PWD)"
