---
meta:
  name:    $(basename $PWD)
  target:  ${fly_target}
  url:     ${fly_target_url}

  initial_version: 1.0.0

  git:
    email:  ((git-commit-email))
    name:   ((git-commit-name))

  dockerhub:
    username: ((dockerhub-username))
    email:    ((dockerhub-email))
    password: ((dockerhub-password))
    repository: (( concat meta.github.owner "/" meta.name ))

  aws:
    bucket:      (( grab meta.pipeline ))
    region_name: us-east-1
    access_key:  ((aws-access-key))
    secret_key:  ((aws-secret-key))

  github:
    owner:  $(jq .OrganizationFields.Name -r ~/.cf/config.json)
    repo:   $(basename $PWD)
    branch: $(git branch --no-color | awk '{print $2}')
    private_key:  ((github-private-key))
    access_token: ((github-access-token))

  slack:
    webhook:       ((slack-webhook))
    username:      ((slack-username))
    icon:          ((slack-icon-url))
    channel:       "#$(basename $PWD)"
